<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\Shipping.Domain\Shipping.Domain.csproj" />
    <ProjectReference Include="..\Shipping.Infrastructure\Shipping.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Shared\CustomTShirts.Events\CustomTShirts.Events.csproj" />
    <ProjectReference Include="..\..\Shared\CustomTShirts.Events.ServiceBus\CustomTShirts.Events.ServiceBus.csproj" />
  </ItemGroup>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
</Project>
